version: 2

models:
  - name: stg_events
    description: "{{ doc('events_table') }}"
    columns:
      - name: event_id
        description: "{{ doc('event_id') }}"
        tests:
          - unique
          - not_null
      - name: event_date
        description: "{{ doc('event_date') }}"
      - name: event_timestamp
        description: "{{ doc('event_timestamp') }}"
      - name: event_name
        description: "{{ doc('event_name') }}"
      - name: event_params
        description: "{{ doc('event_params') }}"
      - name: device_id
        description: "{{ doc('device_id') }}"
      - name: install_id
        description: "{{ doc('install_id') }}"
      - name: device_category
        description: "{{ doc('device_category') }}"
      - name: install_source
        description: "{{ doc('install_source') }}"
  - name: stg_exchange_rates
    description: "{{ doc('exchange_rates_table') }}"
    columns:
      - name: exchange_rate_id
        description: "{{ doc('exchange_rate_id') }}"
        tests:
          - unique
          - not_null
      - name: currency_exchange_date
        description: "{{ doc('currency_exchange_date') }}"
      - name: currency_code
        description: "{{ doc('currency_code') }}"
      - name: usd_per_currency
        description: "{{ doc('usd_per_currency') }}"
      - name: is_extrapolated
        description: "{{ doc('is_extrapolated') }}"
  - name: stg_products
    description: "{{ doc('products_table') }}"
    columns:
      - name: product_name
        description: "{{ doc('product_name') }}"
        tests:
          - not_null
          - unique
      - name: product_type
        description: "{{ doc('product_type') }}"
      - name: product_subtype
        description: "{{ doc('product_subtype') }}"
